export const REQUEST_AIRPORTS = 'REQUEST_AIRPORTS';
export const RECEIVE_AIRPORTS = 'RECEIVE_AIRPORTS';

export const DEPOSIT_TO_ACCOUNT = 'DEPOSIT_TO_ACCOUNT';
export const WITHDRAW_FROM_ACCOUNT = 'WITHDRAW_FROM_ACCOUNT';