/**
 * 
 */
export const REQUEST_AIRPORTS = 'REQUEST_AIRPORTS';
export const RECEIVE_AIRPORTS = 'RECEIVE_AIRPORTS';


/**
 * 
 */
export const DEPOSIT_TO_ACCOUNT = 'DEPOSIT_TO_ACCOUNT';
export const WITHDRAW_FROM_ACCOUNT = 'WITHDRAW_FROM_ACCOUNT';

/**
 * 
 */
export const REQUEST_QUERY_PAY_OPTION = 'REQUEST_QUERY_PAY_OPTION'; 
export const RECEIVE_QUERY_PAY_OPTION = 'RECEIVE_QUERY_PAY_OPTION'; 

export const SELECTED_APP = 'SELECTED_APP';
export const SELECTED_AMOUNT = 'SELECTED_AMOUNT';
export const SHOW_SELECTED_APP = 'SHOW_SELECTED_APP';
export const SELECTED_PAY = 'SELECTED_PAY';



/**
 * 
 */
export const REQUEST_ACTIVITY = 'REQUEST_ACTIVITY';
export const RECEIVE_ACTIVITY = 'RECEIVE_ACTIVITY';